//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace c2cWebsite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.hoadonmuas = new HashSet<hoadonmua>();
            this.merchants = new HashSet<merchant>();
        }
    
        public int customer_id { get; set; }
        [DisplayName("Tên tài khoản")]
        public string username { get; set; }
        public string salt { get; set; }
        [DisplayName("Mật khẩu")]
        [DataType(DataType.Password)]
        public string password { get; set; }
        [DataType(DataType.EmailAddress)]
        [DisplayName("Email")]
        public string email { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ngaydangky { get; set; }
        public int tienao { get; set; }
        public Nullable<bool> tinhtrangkichhoat { get; set; }
        [DisplayName("Họ Tên")]
        public string hoten { get; set; }
        [DisplayName("Ngày Sinh")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ngaysinh { get; set; }
        [DisplayName("Số điện thoại")]
        [DataType(DataType.PhoneNumber)]
        public string sodienthoai { get; set; }
        [DisplayName("Giới tính")]
        public Nullable<bool> gioitinh { get; set; }
        [DisplayName("Địa chỉ")]
        public string diachi { get; set; }
        public Nullable<bool> ismechant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoadonmua> hoadonmuas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<merchant> merchants { get; set; }
    }
}
