//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace c2cWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadonmua
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hoadonmua()
        {
            this.hoadonbans = new HashSet<hoadonban>();
        }
    
        public int hoadonmua_id { get; set; }
        public string noinhan { get; set; }
        public Nullable<int> sosanpham { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<decimal> tongtien { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> hinhthucthanhtoan_id { get; set; }
        public Nullable<int> tinhtranggiaohang_id { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual hinhthucthanhtoan hinhthucthanhtoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoadonban> hoadonbans { get; set; }
        public virtual tinhtranggiaohang tinhtranggiaohang { get; set; }
    }
}
