//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace c2cWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadonban
    {
        public int hoadonban_id { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<System.DateTime> ngayhoanthanh { get; set; }
        public string noigui { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<decimal> thanhtien { get; set; }
        public Nullable<int> sanpham_id { get; set; }
        public Nullable<int> merchant_id { get; set; }
        public Nullable<int> hinhthucthanhtoan_id { get; set; }
        public Nullable<int> tinhtranggiaohang_id { get; set; }
        public Nullable<int> hoadonmua_id { get; set; }
    
        public virtual hinhthucthanhtoan hinhthucthanhtoan { get; set; }
        public virtual hoadonmua hoadonmua { get; set; }
        public virtual merchant merchant { get; set; }
        public virtual sanpham sanpham { get; set; }
        public virtual tinhtranggiaohang tinhtranggiaohang { get; set; }
    }
}
