//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace c2cWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khuyenmai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public khuyenmai()
        {
            this.sanpham_khuyenmai = new HashSet<sanpham_khuyenmai>();
        }
    
        public int khuyenmai_id { get; set; }
        public string tenkhuyenmai { get; set; }
        public Nullable<System.DateTime> ngaybatdau { get; set; }
        public Nullable<System.DateTime> ngayketthuc { get; set; }
        public Nullable<int> muckhuyenmaitoida { get; set; }
        public Nullable<int> merchant_id { get; set; }
    
        public virtual merchant merchant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sanpham_khuyenmai> sanpham_khuyenmai { get; set; }
    }
}
