//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace c2cWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham_khuyenmaihethong
    {
        public int sanpham_id { get; set; }
        public int khuyenmaihethong_id { get; set; }
        public Nullable<int> muckhuyenmai { get; set; }
    
        public virtual khuyenmaihethong khuyenmaihethong { get; set; }
        public virtual sanpham sanpham { get; set; }
    }
}
