//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace c2cWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sanpham()
        {
            this.hinhanhs = new HashSet<hinhanh>();
            this.hoadonbans = new HashSet<hoadonban>();
            this.sanpham_khuyenmai = new HashSet<sanpham_khuyenmai>();
            this.sanpham_khuyenmaihethong = new HashSet<sanpham_khuyenmaihethong>();
            this.sanpham_mausac = new HashSet<sanpham_mausac>();
            this.sanpham_thongsokythuat = new HashSet<sanpham_thongsokythuat>();
        }
    
        public int sanpham_id { get; set; }
        public string tensanpham { get; set; }
        public int tongsoluongton { get; set; }
        public string mota { get; set; }
        public decimal gia { get; set; }
        public Nullable<System.DateTime> ngaydang { get; set; }
        public Nullable<bool> tinhtrangduyet { get; set; }
        public string hinhanh { get; set; }
        public Nullable<bool> tinhtrangkhoa { get; set; }
        public Nullable<int> hangsanpham_id { get; set; }
        public Nullable<int> loaisanpham_id { get; set; }
        public Nullable<int> tinhtrangton_id { get; set; }
        public Nullable<int> merchant_id { get; set; }
    
        public virtual hangsanpham hangsanpham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hinhanh> hinhanhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoadonban> hoadonbans { get; set; }
        public virtual loaisanpham loaisanpham { get; set; }
        public virtual merchant merchant { get; set; }
        public virtual tinhtrangton tinhtrangton { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sanpham_khuyenmai> sanpham_khuyenmai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sanpham_khuyenmaihethong> sanpham_khuyenmaihethong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sanpham_mausac> sanpham_mausac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sanpham_thongsokythuat> sanpham_thongsokythuat { get; set; }
    }
}
